/*
This file was generated by https://github.com/pmndrs/gltfjsx and then
customized manually. It uses drei's new useAnimations hook which extracts
all actions and sets up a THREE.AnimationMixer for it so that you don't have to.
All of the assets actions, action-names and clips are available in its output. 
*/

import { useEffect, useState, useRef } from 'react';
import { useGLTF, useTexture, useAnimations } from '@react-three/drei';
import { a, useSpring } from '@react-spring/three';
import { useLoader } from '@react-three/fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';

const animationStop = (status) => {
  if (status === 'rope' || status === 'idle') {
    return false;
  }
  return true;
};

export default function Model(props) {
  var [y, setY] = useState(0);
  const group = useRef();
  // Fetch model and a separate texture
  const gltf = useLoader(GLTFLoader, 'assets/Basketball_Model.glb');

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, y, 0]} scale={0.02}>
        <primitive object={gltf.scene} />
      </group>
    </group>
  );
}
